#!/usr/bin/env python3
"""
Simple Pomodoro app inspired by spt project.
The app designed to be used with i3blocks.
"""
import os
import socket
from itertools import cycle
from subprocess import call
from time import sleep
from threading import Thread


def notify(text):
    call(["notify-send", "Pomodoro", text])


def daemonize():
    if os.fork() > 0:
        exit()
    os.setsid()
    if os.fork() > 0:
        exit()


class AlredyStartedError(Exception):
    pass


class Cycle:
    def __init__(self, items):
        self._items = items
        self._iter = None
        self.reset()

    def reset(self):
        self._iter = cycle(self._items)

    def __iter__(self):
        return self

    def __next__(self):
        return next(self._iter)


class Pomodoro:
    def __init__(self, cycle):
        self._cycle = cycle
        self._state = "Paused"
        self._remaining = 0
        self._do_reset = False
        self._running = False

    @property
    def state(self):
        state = self._state
        if not self._running:
            state = "Paused"
        minutes, seconds = divmod(self._remaining, 60)
        return "{0} {1:02d}:{2:02d}".format(state, minutes, seconds)

    def toggle(self):
        self._running = not self._running

    def reset(self):
        self._do_reset = True
        self._cycle.reset()

    def start(self):
        for timeout, state, message in self._cycle:
            if self._do_reset:
                self._do_reset = False

            if self._running:
                self._state = state
                notify(message)

            self._remaining = timeout * 60
            while self._remaining:
                if self._do_reset:
                    break
                sleep(1)
                if self._running:
                    self._remaining -= 1
                    self._state = state


class App:
    ADDRESS = "\0pomodoro"
    PAUSE = b"pause"
    RESET = b"reset"
    DISPLAY = b"display"

    def __init__(self, pomodoro):
        self._thread = Thread(target=self._handle_connections)
        self._sock = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
        self._pomodoro = pomodoro

    def run(self):
        try:
            self._sock.bind(self.ADDRESS)
        except socket.error:
            raise AlredyStartedError()

        daemonize()

        Thread(target=self._pomodoro.start).start()
        self._handle_connections()

    def display(self):
        self._send(self.DISPLAY)

    def toggle(self):
        self._send(self.PAUSE)

    def reset(self):
        self._send(self.RESET)

    def _send(self, command):
        self._sock.connect(self.ADDRESS)
        self._sock.sendall(command)
        print(self._sock.recv(32).decode("utf-8"))

    def _handle_connections(self):
        self._sock.listen()
        while True:
            conn, _ = self._sock.accept()
            command = conn.recv(16)
            if command == self.PAUSE:
                self._pomodoro.toggle()
            elif command == self.RESET:
                self._pomodoro.reset()

            conn.sendall(self._pomodoro.state.encode("utf-8"))
            conn.close()


app = App(
    Pomodoro(
        Cycle(
            [
                (25, "Working", "Time to start working!"),
                (5, "Resting", "Time to start resting!"),
                (25, "Working", "Time to start working!"),
                (5, "Resting", "Time to start resting!"),
                (25, "Working", "Time to start working!"),
                (5, "Resting", "Time to start resting!"),
                (25, "Working", "Time to start working!"),
                (15, "Long Break", "Time to take some nap!"),
            ]
        )
    )
)


if __name__ == "__main__":
    try:
        app.run()
    except AlredyStartedError:
        button = os.getenv("BLOCK_BUTTON", "").lower()
        if button == "1":
            app.toggle()
        elif button == "3":
            app.reset()
        else:
            app.display()
